# Generated by Django 5.1.4 on 2025-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_startup_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
