# Generated by Django 5.1.4 on 2025-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_startup_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='founder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
